### ISSUE TITLE
ActivityType enum

### ISSUE THREAD

**Issue by james86** [inexcitus/stravadotnet#16]
Hi,

Not all the ActivityTypes available for manual entry on the Strava website are defined in the ActivityType enum e.g. Crossfit

**Comment by WestDiscGolf** [comment]
Looks like that has been addressed in #21

**Comment by Tylland** [comment]
I think Iceskate in ActivityType is misspelled, maybe should be IceSkate. At least it gives me an exception.

**Comment by inexcitus** [comment]
I just renamed the property, thanks for the info.
