### ISSUE TITLE
nuspec is missing the library?

### ISSUE THREAD

**Issue by slodge** [inexcitus/stravadotnet#27]
I've just installed the nuget package into a v4.6 sample app

It looks like the only thing that gets referenced in the project is the Newtonsoft Json library - not the Strava.Net Assembly itself.

Looking at the downloaded nuspec, I think it's missing the `<files>` section (although maybe my nuspec knowledge is out of date).

Current is:
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
    <metadata>
        <id>Strava.NET</id>
        <version>3.4.1</version>
        <title>Strava.NET - Strava API Framework</title>
        <authors>Sascha Simon</authors>
        <owners>Sascha Simon</owners>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>A small framework that makes using the Strava API a little bit easier.

You can find a Readme file at https://github.com/inexcitus/stravadotnet/

Please send any feedback to strava@sascha-simon.com</description>
        <summary>A small framework that makes using the Strava API a little bit easier.

You can find a Readme file at https://github.com/inexcitus/stravadotnet/

Please send any feedback to strava@sascha-simon.co</summary>
        <releaseNotes>See the full changelog at http://www.sascha-simon.com/strava/changelog</releaseNotes>
        <copyright>Sascha Simon</copyright>
        <tags>Strava, Cycling, Http, REST, API, Biking, Async, 4.5, Client, Sync, Web, JSON, WebRequest, WebResponse</tags>
        <dependencies>
            <group targetFramework=".NETFramework4.5">
                <dependency id="Newtonsoft.Json" version="6.0.5" />
            </group>
        </dependencies>
    </metadata>
</package>
```

I would expect to add something like:

```
<files>		
	<file  src="StravaDotNet.dll" target="lib\net45" />
</files>		
```

If the nuspec/build process itself were in github, I'd have tried to fix it, test it and to send a Pull :) (I'd have tried... can't promise I'd have made it work...)

Thanks for all your work on this library - looks very useful!

Stuart

**Comment by slodge** [comment]
(actually... maybe this is just a v4.6 / vs2015 issue... )

**Comment by inexcitus** [comment]
Hello,

I just updated the package, could you please try again?

Regards,
Sascha

Am 28.03.2016 um 13:33 schrieb Stuart Lodge:

**Comment by slodge** [comment]
Trying 3.4.2 on VS2015 Enterprise with Update 2 (RC)

When I try into a console app set to either .net45 or .net46 then neither get the reference added to stravadotnet assembly (both correctly get a newtonsoft json reference)

**Comment by inexcitus** [comment]
Hello,

Debug or Release configuration?

The project was build using a Debug configuration, maybe that's the problem?

Regards,
Sascha

Am 28.03.2016 um 15:02 schrieb Stuart Lodge:

**Comment by inexcitus** [comment]
Hello again,

I think i messed up the NuGet package before. Can you please try again 
(Version 3.4.3)?

Regards,
Sascha

Am 28.03.2016 um 15:02 schrieb Stuart Lodge:

**Comment by slodge** [comment]
3.4.3 :+1: 

Closing - thanks :)
