### ISSUE TITLE
Get Elevation from Stream

### ISSUE THREAD

**Issue by monteiro-luiz** [inexcitus/stravadotnet#32]
How to get elevation (<ele> gpx tag) from Activity Streams? I'm not sure but Altitude passes the accumulated values and not elevation status to coordinate point. Yes?

**Comment by inexcitus** [comment]
The values aren't accumulated, the altitude stream is the stream you're looking for.

Do you have a sample activity?

**Comment by monteiro-luiz** [comment]
Yes! Activity ID = 768816879 
Getting >>

elevation = client.Streams.GetActivityStream(activityID, StreamType.Altitude, StreamResolution.All)

Return List:

Count = 1881
    (0): 0.0 {Double}
    (1): 3.9 {Double}
    (2): 7.7 {Double}
    (3): 11.7 {Double}
    (4): 16.5 {Double}
    (5): 21.4 {Double}
    (6): 26.7 {Double}
    (7): 33.0 {Double}
    (8): 38.4 {Double}
    (9): 44.1 {Double}
    (10): 49.0 {Double}
    (11): 54.8 {Double}
    (12): 61.5 {Double}
    (13): 68.5 {Double}
    (14): 75.2 {Double}
    (15): 81.6 {Double}
    (16): 98.1 {Double}
    (17): 104.1 {Double}
    (18): 108.8 {Double}
    (19): 112.4 {Double}
    (20): 119.8 {Double}
    (21): 127.2 {Double}
    (22): 133.6 {Double}
    (23): 139.2 {Double}
    (24): 146.7 {Double}
    (25): 154.5 {Double}
    (26): 161.1 {Double}
    (27): 180.1 {Double}
    (28): 187.8 {Double}
    (29): 195.0 {Double}
    (30): 202.1 {Double}
    (31): 210.6 {Double}
    (32): 217.1 {Double}
    (33): 223.1 {Double}
    (34): 230.0 {Double}
    (35): 236.1 {Double}
    (36): 245.0 {Double}
    (37): 251.1 {Double}
    (38): 259.2 {Double}
    (39): 265.2 {Double}
    (40): 273.5 {Double}
    (41): 281.2 {Double}
    (42): 287.9 {Double}
    (43): 292.9 {Double}
    (44): 299.0 {Double}
    (45): 306.7 {Double}
    (46): 312.8 {Double}
    (47): 319.4 {Double}
    (48): 325.2 {Double}
    (49): 329.4 {Double}
    (50): 354.7 {Double}
    (51): 361.4 {Double}
    (52): 368.4 {Double}
    (53): 375.1 {Double}
    (54): 380.4 {Double}
    (55): 389.6 {Double}
    (56): 395.4 {Double}
    (57): 403.4 {Double}
    (58): 410.2 {Double}
    (59): 416.8 {Double}
    (60): 423.3 {Double}
    (61): 427.9 {Double}
    (62): 433.5 {Double}
    (63): 439.9 {Double}
    (64): 444.6 {Double}
    (65): 447.9 {Double}
    (66): 452.1 {Double}
    (67): 455.2 {Double}
    (68): 461.5 {Double}
    (69): 465.7 {Double}
    (70): 471.9 {Double}
    (71): 475.0 {Double}
    (72): 489.9 {Double}
    (73): 494.0 {Double}
    (74): 497.2 {Double}
    (75): 500.2 {Double}
    (76): 504.5 {Double}
    (77): 508.0 {Double}
    (78): 511.8 {Double}
    (79): 515.7 {Double}
    (80): 521.2 {Double}
    (81): 525.9 {Double}
    (82): 530.3 {Double}
    (83): 535.2 {Double}
    (84): 541.8 {Double}
    (85): 546.4 {Double}
    (86): 550.8 {Double}
    (87): 556.0 {Double}
    (88): 562.3 {Double}
    (89): 567.6 {Double}
    (90): 573.4 {Double}
    (91): 579.5 {Double}
    (92): 586.1 {Double}
    (93): 592.7 {Double}
    (94): 598.7 {Double}
    (95): 604.7 {Double}
    (96): 611.0 {Double}
    (97): 617.7 {Double}
    (98): 624.5 {Double}
    (99): 630.8 {Double}

**Comment by inexcitus** [comment]
Hello,

thank you, I will review it. First I thought that it may be the total elevation gain (in relation to the distance), but the ride only has 48 m elevation gain, so that can't be.

I will review this on my iOS implementation, because this implementation is up to date.

**Comment by inexcitus** [comment]
Hello again,

I just checked one of my activities and it seems to be correct:

var stream = client.Streams.GetActivityStream("768776196", Strava.Streams.StreamType.Altitude);

**Comment by monteiro-luiz** [comment]
Is it any relationship to iOS data?

**Comment by inexcitus** [comment]
I haven't tried my iOS framework, i've tested the StravaDotNet one and it worked fine.

**Comment by monteiro-luiz** [comment]
Hummm but me too!

**Comment by monteiro-luiz** [comment]
See my code in VB.NET but compile StravaDotNet and use:

       ```
 Dim token As String = ""
        Dim auth As StaticAuthentication
        Dim client As StravaClient
        Dim after As Date = Now.AddDays(-1)
        Dim before As Date = after.AddDays(1)
        Dim activityID As Integer
        Dim route As List(Of ActivityStream)
        Dim elevation As List(Of ActivityStream)
        
        Try
            auth = New StaticAuthentication(token)
            client = New StravaClient(auth)

            activities = client.Activities.GetActivities(after, before)
            activityID = activities.Item(0).Id

            route = client.Streams.GetActivityStream(activityID, StreamType.LatLng, StreamResolution.All)
            elevation = client.Streams.GetActivityStream(activityID, Strava.Streams.StreamType.Altitude)         

        Catch ex As Exception

        End Try
```

**Comment by monteiro-luiz** [comment]
Hello again! I solved it! I do not know why, but when I put the "xor" latlng and altitude, it worked !!

`streams = client.Streams.GetActivityStream(activityID, StreamType.LatLng Xor StreamType.Altitude)`

Thanks your help! Close it!

**Comment by inexcitus** [comment]
That's nice to hear.
